[ClassVersion("1.0.0"), FriendlyName("cOctopusServerUsernamePasswordAuthentication")]
class cOctopusServerUsernamePasswordAuthentication : OMI_BaseResource
{
  [Key, Description("Name of the Octopus Server instance")] string InstanceName;
  [Write] boolean Enabled;
};
